# Generated by Django 5.2.17 on 2026-09-29 16:45

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("seminar", "Seminar"),
                            ("workshop", "Workshop"),
                            ("sports", "Sports Event"),
                            ("cultural", "Cultural Event"),
                            ("technical", "Technical Event"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("venue", models.CharField(max_length=200)),
                ("max_participants", models.PositiveIntegerField(default=50)),
                (
                    "participation_type",
                    models.CharField(
                        choices=[
                            ("solo", "Solo only"),
                            ("team", "Team only"),
                            ("both", "Solo or Team"),
                        ],
                        default="solo",
                        max_length=10,
                    ),
                ),
                ("max_team_size", models.PositiveSmallIntegerField(default=4)),
                ("rules", models.TextField(blank=True, help_text="One rule per line.")),
                (
                    "student_coordinator_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "student_coordinator_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                (
                    "teacher_coordinator_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "teacher_coordinator_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_posters/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.CharField(max_length=20, unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("BCA", "BCA"),
                            ("BBA", "BBA"),
                            ("BCom", "B.Com"),
                            ("BSc", "B.Sc"),
                            ("BA", "B.A"),
                            ("MCA", "MCA"),
                            ("MBA", "MBA"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("1", "First Year"),
                            ("2", "Second Year"),
                            ("3", "Third Year"),
                        ],
                        max_length=2,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participation_type",
                    models.CharField(
                        choices=[("solo", "Solo"), ("team", "Team")],
                        default="solo",
                        max_length=10,
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=100)),
                (
                    "team_members",
                    models.TextField(blank=True, help_text="One player name per line."),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
                "unique_together": {("student", "event")},
            },
        ),
    ]
